config/routes.rb
Rails.application.routes.draw do
  resources :waste_items

  root 'waste_items#index'

end

app/models/waste_item.rb
class WasteItem < ActiveRecord::Base
  def self.create_cloud
    weights = [*1..80]
    content = self.all.collect{ |item| item.content.downcase.gsub(/[^0-9A-Za-z]\s/, '') }
    word_array = content.join(' ').split(' ')
    word_array.sort_by!{|x| word_array.count(x)}
    word_array = word_array.uniq

    word_objects = ""

    (1..100).step(4).to_a.reverse.each do |n|
      word_objects << "{text:\"#{word_array.pop}\",weight:#{n}},"
    end
    word_objects

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/waste_items_controller.rb
class WasteItemsController < ApplicationController
  before_action :set_waste_item, only: [:show, :edit, :update, :destroy]

  # GET /waste_items
  # GET /waste_items.json
  def index
    @waste_items = WasteItem.all
    @waste_item = WasteItem.new
  end

  # GET /waste_items/1
  # GET /waste_items/1.json
  def show
  end

  # GET /waste_items/new
  def new
    @waste_item = WasteItem.new
  end

  # GET /waste_items/1/edit
  def edit
  end

  # POST /waste_items
  # POST /waste_items.json
  def create
    @waste_item = WasteItem.new(waste_item_params)

    respond_to do |format|
      if @waste_item.save
        format.html { redirect_to waste_items_path, notice: 'Waste item was successfully created.' }
        format.json { render :show, status: :created, location: @waste_item }
      else
        format.html { render :new }
        format.json { render json: @waste_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waste_items/1
  # PATCH/PUT /waste_items/1.json
  def update
    respond_to do |format|
      if @waste_item.update(waste_item_params)
        format.html { redirect_to @waste_item, notice: 'Waste item was successfully updated.' }
        format.json { render :show, status: :ok, location: @waste_item }
      else
        format.html { render :edit }
        format.json { render json: @waste_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waste_items/1
  # DELETE /waste_items/1.json
  def destroy
    @waste_item.destroy
    respond_to do |format|
      format.html { redirect_to waste_items_url, notice: 'Waste item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tag_cloud
    @waste_items = WasteItem.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waste_item
      @waste_item = WasteItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waste_item_params
      params.require(:waste_item).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/waste_items_helper.rb
module WasteItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="assets/img/favicon.png">
    <title>WasteBin</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><b>WasteBin</b></a>
        </div>
      </div>
    </div>

    <div id="headerwrap">
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row mt centered">
          <%= render 'waste_items/tag_cloud'  %>
      </div>
    </div>
  </body>
</html>

app/views/waste_items/_form.html.erb
<%= form_for(@waste_item) do |f| %>
  <% if @waste_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waste_item.errors.count, "error") %> prohibited this waste_item from being saved:</h2>

      <ul>
      <% @waste_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :content, :autofocus => true %>
  </div>
  <div class="actions">
    <%= f.submit "Trash It!", :class => "btn btn-warning btn-lg" %>
  </div>
<% end %>

app/views/waste_items/_tag_cloud.html.erb
<div class="cloud" data-cloud="<%= @waste_items.create_cloud%>" style="width: 800px; height: 600px;"></div>

app/views/waste_items/edit.html.erb
<h1>Editing waste_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @waste_item %> |
<%= link_to 'Back', waste_items_path %>

app/views/waste_items/index.html.erb
<div class="col-lg-6">
<h1>The first step to eliminating waste is identifying it.</h1>
<h3>Enter a new Waste Item</h3>

<%= render 'waste_items/form' %>

<br>

</div>
<div class="col-lg-6">
  <%= image_tag "bin.png", :class => "img-responsive" %>
</div>

app/views/waste_items/new.html.erb
<h1>New waste_item</h1>

<%= render 'form' %>

<%= link_to 'Back', waste_items_path %>

app/views/waste_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @waste_item.content %>
</p>

<%= link_to 'Edit', edit_waste_item_path(@waste_item) %> |
<%= link_to 'Back', waste_items_path %>